export const data = [
    {
        id: 1,
        question: 'What does HTML stand for?',
        option1: 'Hyper Text Markup Language',
        option2: 'High Text Markup Language',
        option3: 'Hyper Tabular Markup Language',
        option4: 'None of the above',
        correct: 'option1',
    },
    {
        id: 2,
        question: 'What does CSS stand for?',
        option1: 'Colorful Style Sheets',
        option2: 'Creative Style Sheets',
        option3: 'Cascading Style Sheets',
        option4: 'Computer Style Sheets',
        correct: 'option3',
    },
    {
        id: 3,
        question: 'Which tag defines an internal style sheet?',
        option1: 'script tag',
        option2: 'style tag',
        option3: 'css tag',
        option4: 'link tag',
        correct: 'option2',
    },
    {
        id: 4,
        question: 'CSS property for background color?',
        option1: 'color',
        option2: 'bgcolor',
        option3: 'background-color',
        option4: 'background',
        correct: 'option3',
    },
    {
        id: 5,
        question: 'How do you create an alert box?',
        option1: 'msg("Hello World");',
        option2: 'alertBox("Hello World");',
        option3: 'msgBox("Hello World");',
        option4: 'alert("Hello World");',
        correct: 'option4',
    },
    {
        id: 6,
        question: 'How do you declare a JS function?',
        option1: 'function:myFunction()',
        option2: 'function = myFunction()',
        option3: 'function myFunction()',
        option4: 'def myFunction()',
        correct: 'option3',
    },
    {
        id: 7,
        question: 'How do you call a function "myFunction"?',
        option1: 'call myFunction()',
        option2: 'myFunction()',
        option3: 'call function myFunction()',
        option4: 'execute myFunction()',
        correct: 'option2',
    },
    {
        id: 8,
        question: 'Which operator is for assignment?',
        option1: '=',
        option2: '*',
        option3: '-',
        option4: 'x',
        correct: 'option1',
    },
    {
        id: 9,
        question: 'What is the correct syntax for a JS array?',
        option1: 'var colors = (1:"red")',
        option2: 'var colors = "red"',
        option3: 'var colors = ["red"]',
        option4: 'var colors = 1 = ("red")',
        correct: 'option3',
    },
    {
        id: 10,
        question: 'How does a FOR loop start?',
        option1: 'for (i = 0; i <= 5; i++)',
        option2: 'for (i <= 5; i++)',
        option3: 'for i = 1 to 5',
        option4: 'for (i = 0; i <= 5)',
        correct: 'option1',
    }
]
